### ISSUE TITLE
CMakeLists min cmake version required

### ISSUE THREAD

**Issue by thomas-roos** [aws-samples/aws-iot-securetunneling-localproxy#167]
**Describe the bug**

CMake version 3.30 complains about missing min cmake version:
```
|   No cmake_minimum_required command is present.  A line of code such as
ERROR: Task (/codebuild/output/src1843937046/src/actions-runner/_work/meta-aws/meta-aws/meta-aws/recipes-iot/aws-iot-securetunneling-localproxy/aws-iot-securetunneling-localproxy_git.bb:do_configure) failed with exit code '1'
| 
|     cmake_minimum_required(VERSION 3.30)
| 
|   should be added at the top of the file.  The version specified may be lower
|   if you wish to support older CMake versions for this project.  For more
|   information run "cmake --help-policy CMP0000".
```

I suggest min version  3.22 or older as this is the oldest version on a Yocto lts release.

```
cmake_minimum_required(VERSION 3.22)
```

**Comment by ig15** [comment]
Thanks @thomas-roos for raising the ticket.

Closing the ticket since the issue has been fixed in the latest patch update of the Yocto build system:
https://github.com/aws4embeddedlinux/meta-aws/blob/master-next/recipes-iot/aws-iot-securetunneling-localproxy/files/0004-cmake-version.patch

The suggested patch updates maybe integrated into the codebase at a later point of time after consideration of requirements and impact.
