### ISSUE TITLE
Localproxy dependencies (boost_1_69_0) not getting installed

### ISSUE THREAD

**Issue by sidharthism** [aws-samples/aws-iot-securetunneling-localproxy#53]
Requirement : To connect to our remote devices (Raspberry Pi), we need to use localproxy in source mode i.e on my machine to establish the source part of tunnel.
Instructions followed : https://www.youtube.com/watch?v=Vq67jKZTR-c , AWS IoT Secure Tunneling docs . (cmake version 3.13.4 and C++14 compiler were used as per the docs)
Issues faced : Able to install the aws-iot-client by following the instructions on GitHub - awslabs/aws-iot-device-client
On our machine, tried installing localproxy by following the instructions on https://github.com/aws-samples/aws-iot-securetunneling-localproxy#building-the-local-proxy-from-source . The **boost_1_69_0 dependency** installation which was running for 4 hours and the installation didn't complete. Also > 6gb of space was getting used. Also **would like to know what are the exact boost libraries that localproxy requires**.

**Steps**

1.  Following instructions in https://github.com/aws-samples/aws-iot-securetunneling-localproxy#building-the-local-proxy-from-source. STEP 1 in above mentioned instruction is for installing zlib which is installed successfully.
2.  (ISSUE in this step) STEP 2 is to install boost dependency (boost_1_69_0). 
> wget https://boostorg.jfrog.io/artifactory/main/release/1.69.0/source/boost_1_69_0.tar.gz -O /tmp/boost.tar.gz
tar xzvf /tmp/boost.tar.gz
cd boost_1_69_0
./bootstrap.sh
sudo ./b2 install **(This step ran for more than 4 hours and installation is not being completed)**

**Environment**

- Distributor ID: Debian
- Description:    Debian GNU/Linux 10 (buster)
- Release:        10
- Kernel: 4.19.0-16-amd64
- Architecture: x86-64

**Comment by kareali** [comment]
@sidharthism Could you update the issue to provide the following information

**Describe the bug**

A clear and concise description of what the bug is.

**To Reproduce**

Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**

A clear and concise description of what you expected to happen.

**Actual behavior**

A clear and concise description of what actually happened.

**Logs**

If applicable, add full logs of errors and outputs to help explain your problem. Preferabbly, you can also [increase the verbosity](https://github.com/aws-samples/aws-iot-securetunneling-localproxy#options-set-via-command-line-arguments), for example to enable debug logs for the localproxy, you can use the cli option `-v 6`

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu]
 - Version [e.g. 16]
 - Architecture: [e.g. x86-64 or x86-32]
 - Localproxy commit: [e.g. [8980ea8e0190c7e8fd942f2bce8bfc01aa6a6a52](https://github.com/aws-samples/aws-iot-securetunneling-localproxy/commit/8980ea8e0190c7e8fd942f2bce8bfc01aa6a6a52)]

**Additional context**

Add any other context about the problem here.

**Comment by kareali** [comment]
No response, closing the issue.
