### ISSUE TITLE
Wrong version error, when trying to connect directly to endpoint

### ISSUE THREAD

**Issue by dkatipamula** [aws-samples/aws-iot-securetunneling-localproxy#54]
[Edited]
Hi,

I am trying to reach an AWS secure tunnel proxy via my own proxy. I was wondering if anyone has any suggestions regarding that.

Something like this:
[localproxy]->[custom proxy]->[secure tunnel proxy server] 

I can get directly to the secure tunnel proxy server by using the -e option. But I would like to have an other proxy in between (customer requirement). Any help is greatly appreciated.

Thanks.

**Comment by kareali** [comment]
Hi @dkatipamula Could you update the issue to provide the following?

**Describe the bug**

A clear and concise description of what the bug is.

**To Reproduce**

Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**

A clear and concise description of what you expected to happen.

**Actual behavior**

A clear and concise description of what actually happened.

**Logs**

If applicable, add full logs of errors and outputs to help explain your problem. Preferabbly, you can also [increase the verbosity](https://github.com/aws-samples/aws-iot-securetunneling-localproxy#options-set-via-command-line-arguments), for example to enable debug logs for the localproxy, you can use the cli option `-v 6`

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu]
 - Version [e.g. 16]
 - Architecture: [e.g. x86-64 or x86-32]
 - Localproxy commit: [e.g. [8980ea8e0190c7e8fd942f2bce8bfc01aa6a6a52](https://github.com/aws-samples/aws-iot-securetunneling-localproxy/commit/8980ea8e0190c7e8fd942f2bce8bfc01aa6a6a52)]

**Additional context**

Add any other context about the problem here.

**Comment by dkatipamula** [comment]
Hi @kareali 

I have updated my post. I am looking for some suggestions, any help is greatly appreciated.

Thanks.

**Comment by kareali** [comment]
hi @dkatipamula , do you mean that you wan to connect via a web proxy (something like squid for example)?

**Comment by kareali** [comment]
No response, closing the issue.
