### ISSUE TITLE
The behaviour of latest version of local proxy seems different from the old versions of local proxy 

### ISSUE THREAD

**Issue by karanberiwal** [aws-samples/aws-iot-securetunneling-localproxy#64]
I had built the latest version of local proxy on centos with all dependencies installed. The local proxy so was built successfully  . I tried running the local proxy on an another centos machine but it failed stating dependencies are not installed. The previous version used to work. It seems the latest so file of local proxy is not bundled up with the required dependencies . Request more information on this behaviour.

**Comment by kareali** [comment]
I need more information, could you please fill a bug report?

**Describe the bug**

A clear and concise description of what the bug is.

**To Reproduce**

Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**

A clear and concise description of what you expected to happen.

**Actual behavior**

A clear and concise description of what actually happened.

**Logs**

If applicable, add full logs of errors and outputs to help explain your problem. Preferabbly, you can also [increase the verbosity](https://github.com/aws-samples/aws-iot-securetunneling-localproxy#options-set-via-command-line-arguments), for example to enable debug logs for the localproxy, you can use the cli option `-v 6`

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu]
 - Version [e.g. 16]
 - Architecture: [e.g. x86-64 or x86-32]
 - Localproxy commit: [e.g. [8980ea8e0190c7e8fd942f2bce8bfc01aa6a6a52](https://github.com/aws-samples/aws-iot-securetunneling-localproxy/commit/8980ea8e0190c7e8fd942f2bce8bfc01aa6a6a52)]

**Additional context**

Add any other context about the problem here.

**Comment by kareali** [comment]
Also check issue #62 and PR #63 , it would explain your problem if you're not using the latest commit.

**Comment by kareali** [comment]
Closing the issue, feel free to re-open it when you're able to provide the necessary information.
