### ISSUE TITLE
Please provide Windows binaries

### ISSUE THREAD

**Issue by Carsten-Holbach** [aws-samples/aws-iot-securetunneling-localproxy#66]
Hey!

Do you think it would be possible to provide Windows binaries? I think it would go a long way to making this feature more accessible, without having to go through the process to compile first for a situation where somebody would really like to do troubleshooting on a Thing (like I would like to now).

Thanks!

**Comment by ChelesaPan-AWS** [comment]
Hi, 
We are considering this as a feature backlog and will let you know when it is available. 

Thank you!

**Comment by HarshGandhi-AWS** [comment]
Hello @Carsten-Holbach  ,

Thank-you for your feedback, this feature has been requested by many of our customers, and that will be a strong influence on the prioritization of this feature. However, at this time we cannot provide a date for this feature. 

Closing this issue now, will post update once the issue is launched. 

Thank you,
Harsh Gandhi
